### PR TITLE
OSP-131: BOSI Ocata readiness

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @sarath-kumar @padubidry 

 - moves all old templates to separate stable/newton directory
 - everything under master now has only Ocata and upwards

question - the modification for `roles_data.yaml` goes as part of deployment guide?
we also removed agent_enabled for both p-only and pv deployment's bigswitch-(p/pv).yaml - that stays as it is? Or should I give it a try with the properties set - to see if it makes a diff?

PS: ignore the big green under origin/stable/newton - its because its now a hard new directory instead of a symlink. pay close attention to the updates under master - that is the one pointed by origin/stable/ocata.

### CODE REVIEW

**Comment by padubidry** [comment]
agent is already commented out in my yaml files

**Comment by sarath-kumar** [comment]
Instead of stable/master; do you want to call it stable/ocata (like stable/newton). That way, we don't have to archive stable/master -> stable/ocata in future. We just need to create new stable/pike and delete stable/newton.

**Comment by wolverineav** [comment]
> Instead of stable/master; do you want to call it stable/ocata (like stable/newton). That way, we don't have to archive stable/master -> stable/ocata in future. We just need to create new stable/pike and delete stable/newton.

so the idea is to have just `master` and let others be soft-link to master. but i think after 2 releases, its not worked as i expected :P its usually just the latest stable/release -> master and the rest being a hard directory with archived yaml and scripts.
let me go through the build jobs once, to see that it won't break anything and then update the directory structure.
i'll have that in a separate PR, after one stable/ocata tarball is ready. so prashanth can start testing with the regular deployment steps :)

**Comment by sarath-kumar** [comment]
Sounds good. ACK

**Pull request merged**
