### PR TITLE
BVS-6867: fix bosi to pick right version of bsnstacklib

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @sarath-kumar 

 - thanks for the catch and suggesting fix here instead of stacklib version bump :)
 - this was easier than i thought. thanks to @xinwu for that.

### CODE REVIEW

**Comment by wolverineav** [comment]
FYI - `horizon-bsn` uses the same version string. but this is still fine, since we run `pip install --upgrade` so it always picks the highest returned version.

**Comment by wolverineav** [comment]
merging this now for testing..

**Comment by sarath-kumar** [comment]
Changes look fine

**Comment by wolverineav** [comment]
> Changes look fine

gracias!

**Pull request merged**
