### PR TITLE
OSP-227: update image tag to pick latest stable container image

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @sarath-kumar @WeifanFu-bsn 

- trivial changes to bump version

### CODE REVIEW

**Comment by sarath-kumar** [comment]
Restart should be only if the ivs config file changed, right? Are you planning to add that logic here?

**Comment by wolverineav** [comment]
> Restart should be only if the ivs config file changed, right? Are you planning to add that logic here?

that should be part of os-net-config. adding it via a patch like this doesn't seem feasible.
because the persistence logic to read before update is not available.

**Comment by sarath-kumar** [comment]
You mean, that logic will need editing more thatn the impl_cfg file, which we are not patching in customize.sh?

**Comment by wolverineav** [comment]
> You mean, that logic will need editing more thatn the impl_cfg file, which we are not patching in customize.sh?

oops - my bad - i thought i added `sed` commands to replace the string - that's how i've been patching for testing other fixes for containers.
did not realize i'm pasting the whole file 🤦🏻‍♂️
using `sed` to selectively replace strings with extra code would've been non-feasible - is what I meant.
my bad :)
yes - the replace logic is part of os-net-config/impl_ifcfg.py and should be doable.
this PR was just to unblock Prashanth asap, so didn't spend that time. i'll open another PR with the proper fix to restart only when config changed 👍🏼
sorry about the confusion :)

**Comment by sarath-kumar** [comment]
Cool, thy shall pass...

**Pull request merged**
