### PR TITLE
update yaml files for RHOSP 10

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @sarath-kumar 
CC: @padubidry 

updated/added the following:
 - bigswitch-config-<p/pv>.yaml
 - network-environment.yaml
 - first-boot.yaml

moved existing master to mitaka and liberty points to mitaka.
newton and ocata to point to master with the updates.

### CODE REVIEW

**Comment by wolverineav** [comment]
@padubidry I couldn’t find `bigswitch-p.yaml` in the directory you mentioned. I believe the changes would be similar to the ones in `bigswitch-pv.yaml`. But some of the properties that are diff between p and pv in the old files are not available in the new one (mostly the ovs related):

```
bsn@bcf-controller-vm:~/work/bosi$ diff bosi/rhosp_resources/master/yamls/bigswitch-config-p.yaml bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml 
8a9
>     neutron::agents::l3::enabled: false
14a16
>   NeutronServicePlugins: bsn_l3,bsn_service_plugin
18,21c20,23
<     neutron::agents::ml2::ovs::manage_vswitch: true    << P-only required and missing
<     neutron::agents::ml2::ovs::enabled: true           << P-only required and missing
<     neutron::agents::bigswitch::lldp_enabled: true
<     neutron::agents::bigswitch::agent_enabled: false
---
>     neutron::agents::ml2::ovs::manage_vswitch: false
>     neutron::agents::ml2::ovs::enabled: false
>     neutron::agents::bigswitch::lldp_enabled: false
>     neutron::agents::bigswitch::agent_enabled: true
bsn@bcf-controller-vm:~/work/bosi$
```

**Comment by padubidry** [comment]
created big switch-p.yaml in the same location.

**Comment by padubidry** [comment]
network-enviorment yamls needs to be bundled for all IVS , NFV , SRIOV

**Comment by wolverineav** [comment]
> network-enviorment yamls needs to be bundled for all IVS , NFV , SRIOV

i believe you mean to say `network-environment.yaml` should be separate for 3 different switches? i've added those separately, the comment should've been clearer.

i've updated the `bigswitch-p.yaml`

**Comment by wolverineav** [comment]
merging this change for future tarballs

**Pull request merged**
