### PR TITLE
OSP-139: add pre-deploy bridge validation script for yamls

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @sarath-kumar @padubidry 

 - if we perform these checks before deployment, would save a lot
   of time debugging later
 - separate files for ocata and newton since the path in yaml is
   different for both of them

### CODE REVIEW

**Comment by wolverineav** [comment]
ping! i'll merge this by eod today. its a relatively trivial change that won't affect regular BOSI work and can be updated for feature addition or patching.

**Comment by sarath-kumar** [comment]
We already have a yaml parser script at https://github.com/bigswitch/bosi/blob/master/bosi/rhosp_resources/master/yamls/yaml_syntax_check.py

I think it is better to merge the two instead?

**Comment by wolverineav** [comment]
yep, i thought so at first. but that one just does blind syntax check.
i can probably rename that to have a little more meaning and add this as an option to pass controller/compute yaml file. since others don't have bridge info.
👍

**Comment by sarath-kumar** [comment]
Yeah, renaming and merging with option for controller/compute sounds like a good plan

**Comment by wolverineav** [comment]
@sarath-kumar for reference, this is the updated `yaml_validate.py` that does both:
```
bsn@bsn:~/work/bosi/bosi$ python rhosp_resources/master/yamls/yaml_validate.py -h
usage: yaml_validate.py [-h] [--bridge BRIDGE] [--syntax SYNTAX]

optional arguments:
  -h, --help       show this help message and exit
  --bridge BRIDGE  RHOSP controller.yaml or compute.yaml with the bridge
                   configuration to be validated.
  --syntax SYNTAX  Find all YAML files in the input directory and validate
                   their syntax.
bsn@bsn:~/work/bosi/bosi$ 
bsn@bsn:~/work/bosi/bosi$ python rhosp_resources/master/yamls/yaml_validate.py 
Please specify at least one option - either --bridge or --syntax
bsn@bsn:~/work/bosi/bosi$ 
```

i'll go ahead with merge, unless the arg naming needs a change :)

**Comment by wolverineav** [comment]
[oh, forgot you're out for kubecon starting today]
acking for now. do let me know your comments. i'll update it, as usual :)

**Pull request merged**
